language: python

python:
  - 3.6

services:
  - postgresql

env:
    DATABASE_URL='postgres://postgres@localhost:5432/test'

install:
  - pip install -r requirements.txt
  - pip install django==3.0.1
  - pip install dj-database-url
  - pip install psycopg2 --quiet

script:
  - python run_tests.py
